### ISSUE TITLE
提供一些提交storm topology的脚本就更好了。

### ISSUE THREAD

**Issue by lynchlee** [Paleozoic/storm_spring_boot_demo#1]

**Comment by Paleozoic** [comment]
提交拓扑的命令由[buildStormCmd.java](https://github.com/Paleozoic/storm_spring_boot_demo/blob/master/src/test/java/com/maxplus1/buildStormCmd.java)生成。依赖的jars会在mvn package的时候自动提取到target/libs。

**Comment by Paleozoic** [comment]
由于SpringBoot重写了ClassLoader，在集群模式下提交拓扑加载的Jar在Storm是无法识别的。不过咱们可以模拟SpringBoot在IDE下的运行情况，实现可在StormCluster上运行的Package方式。

**Comment by Paleozoic** [comment]
已更新。
