### ISSUE TITLE
Spout, Bolt 注入的问题

### ISSUE THREAD

**Issue by wurangbo** [Paleozoic/storm_spring_boot_demo#7]
你的例子中没有涉及到在bolt，spout 注入对象，如下是你的启动类
        ConfigurableApplicationContext context = SpringApplication.run(DemoApplication.class, args);
        AppMain appMain = context.getBean(AppMain.class);
        appMain.Laugher();
        SpringApplication.exit(context);
如果在bolt，spout中用  context.getBean去获取对象实力就会出现空引用，因为SpringApplication.exit，
如果不exit，则会出现提交过程没有办法完成的情况。

**Comment by Paleozoic** [comment]
抱歉，最近没看issuse。
你是想动态获取Bean么？
你可以试试让AppMain 这个类实现ApplicationContextAware这个接口，然后获取Spring上下文。
